### ISSUE TITLE
Debian Nodes

### ISSUE THREAD

**Issue by xLink** [darkscience/ds-salt#5]
allow salt scripts to configure Debian machines untill we are satisfied & have a working version of fBSD on linode

**Comment by dijit** [comment]
Not required for migration of hub, probably required before that. need to add additional milestone for incorporating darchoods.

**Comment by dijit** [comment]
Fixed in https://github.com/darkscience/ds-salt/commit/61973964b1023078c7c23c5beaf6f360af76e61c
