### ISSUE TITLE
Oper Snomasks

### ISSUE THREAD

**Issue by xLink** [darkscience/ds-salt#9]
This is in reference to nara's & my own snomasks.

We are basically requesting to be able to see network connections & local and remote server connections.

**Comment by x-communication** [comment]
Expanding on that, typically I'm the only late night oper and I believe it would be wise to have conn info available in case I'm the only one online to react to things. It's better for the network when staff is not being impaired due to differences in "power."

**Comment by scub** [comment]
Snomasks should default to the following for operators - and disabled on a per-user basis for those who do not wish to see this information.

```
+s +ACGJKLNOQXacdgjklnoqtx
```

**Comment by dijit** [comment]
added snomasks to channel: #services in https://github.com/darkscience/ds-salt/commit/a562cd89fce186904e2fbd710b460674596ee74b

**Comment by xLink** [comment]
#services is now throwing 3 msgs for each entry, so getting better, but still not right

**Comment by dijit** [comment]
Changed the masks setting to only spam local logs.
